[build-system]
build-backend = "maturin"
requires = ["maturin>=1.1,<2.0"]

[project]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "numpy>=1.25.0",
    "opencv-python>=4.8",
    "maturin>=1.7.0",
    "pytest>=7.4.0",
    "pytest-xdist>=3.4.0",
    "typing-extensions",
    "pip",
    "rlenv@git+https://github.com/yamoling/rlenv.git@v1.0.4",
]
description = "A fast Multi-Agent Reinforcement Learning Environment"
keywords = [
    "Reinforcement Leanring",
    "Multi Agent Reinforcement Learning",
    "Environment",
    "marl",
    "rl",
]
name = "laser-learning-environment"
readme = "readme.md"
requires-python = ">=3.10,<4.0"
version = "0.2.7"

[[project.authors]]
email = "yannick.molinghen@ulb.be"
name = "Yannick Molinghen"

[tool.maturin]
features = ["pyo3/extension-module"]
python-source = "python"

[tool.pylint.format]
max-line-length = 140

[tool.pytest.ini_options]
addopts = "-n 2"
pythonpath = ["python"]
testpaths = ["python/tests"]

[tool.ruff]
line-length = 140
