[build-system]
build-backend = "maturin"
requires = ["maturin>=1.1,<2.0"]

[tool.maturin]
features = ["pyo3/extension-module"]
python-source = "python"

[tool.poetry]
authors = ["Yannick Molinghen <yannick.molinghen@ulb.be>"]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: 3",
]
description = "Laser Learning Environment (LLE) for Multi-Agent Reinforcement Learning"
name = "lle"
readme = "readme.md"
version = "0.2.7"

[tool.poetry.dependencies]
numpy = "^2.0"
opencv-python = "^4.8.1.78"
python = ">=3.10,<3.13"

[tool.poetry.dependencies.rlenv]
git = "https://github.com/yamoling/rlenv.git"
tag = "v1.0.4"

[tool.poetry.group.dev.dependencies]
maturin = "^1.7.0"
pytest = "^7.4.0"
pytest-xdist = "^3.4.0"

[tool.pylint.format]
max-line-length = 140

[tool.pytest.ini_options]
addopts = "-n 2"
pythonpath = ["python"]
testpaths = ["python/tests"]

[tool.ruff]
line-length = 140
