name: Test

on:
  push:
    branches:
      - dev
      - master
    tags:
      - '*'
permissions:
  contents: read

jobs:
  test:
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'}}
    name: 🧪 Run tests
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        target:
          - x86_64
          - aarch64
        python-version: 
          - '3.10'
          - '3.11'
          - '3.12'
        exclude:
          - os: windows-latest
            target: 'aarch64'

    runs-on: ${{ matrix.os }}
    steps:
      # Checkout
      - uses: actions/checkout@v4
      # Rust 
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Rust tests
        run: |
          cargo build
          cargo test

      # Python
      - name: Install Python
        uses: actions/setup-python@v5
        with: 
          python-version: ${{ matrix.python-version }}
      - name: Install UV
        uses: yezz123/setup-uv@v4
        with:
          uv-version: 0.3.0
      - name: Pytest
        run: |
          uv sync
          uv run maturin dev
          uv run pytest
